#!/bin/sh

alias ls="lsd" # LS alternative, sudo pacman -S lsd
alias python="python3" # Fix python fucking piece of shit
alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gc='git commit -v'
alias gd='git diff'
alias gp='git push'
alias gst='git status'

# For ESP8266 development
alias get_lx106='export PATH="$PATH:$HOME/esp/xtensa-lx106-elf/bin"'
