icons = "awesome5"

[theme]
name = "modern"

[theme.overrides]
critical_bg = "#E06C75B2"
critical_fg = "#282C34"

warning_bg  = "#282C34B2"
warning_fg  = "#E06C75"

info_bg     = "#282C34B2"
info_fg     = "#E06C75"

idle_bg     = "#282C34B2"
idle_fg     = "#ABB2BF"

good_bg     = "#282C34B2"
good_fg     = "#61AFEF"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization} {frequency}"

[[block]]
block = "temperature"
collapsed = false
interval = 5
format = "{max}C"
good = 50
idle = 60
info = 80

[[block]]
block = "memory"
format_mem = "{mem_used;M}"
display_type = "memory"

[[block]]
block = "net"
device = "wlan0"
format = "{ssid} {signal_strength} {ip}"
interval = 5

[[block]]
driver = "pulseaudio"
block = "sound"
step_width = 3

[[block]]
block = "battery"
interval = 10
driver = "upower"
format = " {percentage} {time}"

[[block]]
block = "time"
format = "%a %d/%m %R"
interval = 60
